global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "doan-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "doan-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
   
