// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accommodation.sql

package database

import (
	"context"
	"encoding/json"
)

const checkAccommodationExists = `-- name: CheckAccommodationExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_accommodation` + "`" + `
        WHERE
            ` + "`" + `id` + "`" + ` = ?
            AND ` + "`" + `is_deleted` + "`" + ` = 0
    )
`

func (q *Queries) CheckAccommodationExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAccommodationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkAccommodationExistsByAdmin = `-- name: CheckAccommodationExistsByAdmin :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_accommodation` + "`" + `
        WHERE
            ` + "`" + `id` + "`" + ` = ?
    )
`

func (q *Queries) CheckAccommodationExistsByAdmin(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAccommodationExistsByAdmin, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAccommodation = `-- name: CountAccommodation :one
SELECT
    COUNT(*)
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
`

func (q *Queries) CountAccommodation(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccommodation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccommodationByCity = `-- name: CountAccommodationByCity :one
SELECT
    COUNT(*)
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `city` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
`

func (q *Queries) CountAccommodationByCity(ctx context.Context, city string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccommodationByCity, city)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccommodationByManager = `-- name: CountAccommodationByManager :one
SELECT
    COUNT(*)
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `manager_id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

func (q *Queries) CountAccommodationByManager(ctx context.Context, managerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccommodationByManager, managerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccommodationOfManager = `-- name: CountAccommodationOfManager :one
SELECT
    COUNT(*)
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `manager_id` + "`" + ` = ?
`

func (q *Queries) CountAccommodationOfManager(ctx context.Context, managerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccommodationOfManager, managerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccommodation = `-- name: CreateAccommodation :exec
INSERT INTO
    ` + "`" + `ecommerce_go_accommodation` + "`" + ` (
        ` + "`" + `id` + "`" + `,
        ` + "`" + `manager_id` + "`" + `,
        ` + "`" + `country` + "`" + `,
        ` + "`" + `name` + "`" + `,
        ` + "`" + `city` + "`" + `,
        ` + "`" + `district` + "`" + `,
        ` + "`" + `description` + "`" + `,
        ` + "`" + `facilities` + "`" + `,
        ` + "`" + `gg_map` + "`" + `,
        ` + "`" + `address` + "`" + `,
        ` + "`" + `rating` + "`" + `,
        ` + "`" + `rules` + "`" + `,
        ` + "`" + `created_at` + "`" + `,
        ` + "`" + `updated_at` + "`" + `
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAccommodationParams struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Address     string
	Rating      uint8
	Rules       json.RawMessage
	CreatedAt   uint64
	UpdatedAt   uint64
}

func (q *Queries) CreateAccommodation(ctx context.Context, arg CreateAccommodationParams) error {
	_, err := q.db.ExecContext(ctx, createAccommodation,
		arg.ID,
		arg.ManagerID,
		arg.Country,
		arg.Name,
		arg.City,
		arg.District,
		arg.Description,
		arg.Facilities,
		arg.GgMap,
		arg.Address,
		arg.Rating,
		arg.Rules,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAccommodation = `-- name: DeleteAccommodation :exec
UPDATE ` + "`" + `ecommerce_go_accommodation` + "`" + `
SET
    ` + "`" + `is_deleted` + "`" + ` = 1,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

type DeleteAccommodationParams struct {
	UpdatedAt uint64
	ID        string
}

func (q *Queries) DeleteAccommodation(ctx context.Context, arg DeleteAccommodationParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccommodation, arg.UpdatedAt, arg.ID)
	return err
}

const getAccommodationById = `-- name: GetAccommodationById :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
`

type GetAccommodationByIdRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Address     string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
}

func (q *Queries) GetAccommodationById(ctx context.Context, id string) (GetAccommodationByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationById, id)
	var i GetAccommodationByIdRow
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.Country,
		&i.Name,
		&i.City,
		&i.District,
		&i.Address,
		&i.Description,
		&i.Facilities,
		&i.GgMap,
		&i.Rules,
		&i.Rating,
	)
	return i, err
}

const getAccommodationByIdByAdmin = `-- name: GetAccommodationByIdByAdmin :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `,
    ` + "`" + `is_deleted` + "`" + `,
    ` + "`" + `is_verified` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

type GetAccommodationByIdByAdminRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Address     string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
	IsDeleted   uint8
	IsVerified  uint8
}

func (q *Queries) GetAccommodationByIdByAdmin(ctx context.Context, id string) (GetAccommodationByIdByAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationByIdByAdmin, id)
	var i GetAccommodationByIdByAdminRow
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.Country,
		&i.Name,
		&i.City,
		&i.District,
		&i.Address,
		&i.Description,
		&i.Facilities,
		&i.GgMap,
		&i.Rules,
		&i.Rating,
		&i.IsDeleted,
		&i.IsVerified,
	)
	return i, err
}

const getAccommodationByIdNoVerify = `-- name: GetAccommodationByIdNoVerify :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `,
    ` + "`" + `is_deleted` + "`" + `,
    ` + "`" + `is_verified` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

type GetAccommodationByIdNoVerifyRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Address     string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
	IsDeleted   uint8
	IsVerified  uint8
}

func (q *Queries) GetAccommodationByIdNoVerify(ctx context.Context, id string) (GetAccommodationByIdNoVerifyRow, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationByIdNoVerify, id)
	var i GetAccommodationByIdNoVerifyRow
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.Country,
		&i.Name,
		&i.City,
		&i.District,
		&i.Address,
		&i.Description,
		&i.Facilities,
		&i.GgMap,
		&i.Rules,
		&i.Rating,
		&i.IsDeleted,
		&i.IsVerified,
	)
	return i, err
}

const getAccommodationNameById = `-- name: GetAccommodationNameById :one
SELECT
    ` + "`" + `name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

func (q *Queries) GetAccommodationNameById(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationNameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getAccommodations = `-- name: GetAccommodations :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
`

type GetAccommodationsRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	Address     string
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
}

func (q *Queries) GetAccommodations(ctx context.Context) ([]GetAccommodationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsRow
	for rows.Next() {
		var i GetAccommodationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Description,
			&i.Facilities,
			&i.Address,
			&i.GgMap,
			&i.Rules,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsByCity = `-- name: GetAccommodationsByCity :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rating` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `city` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
`

type GetAccommodationsByCityRow struct {
	ID       string
	Country  string
	Name     string
	City     string
	District string
	Address  string
	GgMap    string
	Rating   uint8
}

func (q *Queries) GetAccommodationsByCity(ctx context.Context, city string) ([]GetAccommodationsByCityRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsByCityRow
	for rows.Next() {
		var i GetAccommodationsByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Address,
			&i.GgMap,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsByCityWithPagination = `-- name: GetAccommodationsByCityWithPagination :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `,
    ` + "`" + `is_deleted` + "`" + `,
    ` + "`" + `is_verified` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `city` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
LIMIT
    ?
OFFSET
    ?
`

type GetAccommodationsByCityWithPaginationParams struct {
	City   string
	Limit  int32
	Offset int32
}

type GetAccommodationsByCityWithPaginationRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	Address     string
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
	IsDeleted   uint8
	IsVerified  uint8
}

func (q *Queries) GetAccommodationsByCityWithPagination(ctx context.Context, arg GetAccommodationsByCityWithPaginationParams) ([]GetAccommodationsByCityWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsByCityWithPagination, arg.City, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsByCityWithPaginationRow
	for rows.Next() {
		var i GetAccommodationsByCityWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Description,
			&i.Facilities,
			&i.Address,
			&i.GgMap,
			&i.Rules,
			&i.Rating,
			&i.IsDeleted,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsByManager = `-- name: GetAccommodationsByManager :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `is_deleted` + "`" + ` = 0
    AND ` + "`" + `manager_id` + "`" + ` = ?
`

type GetAccommodationsByManagerRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Address     string
	Rules       json.RawMessage
	Rating      uint8
}

func (q *Queries) GetAccommodationsByManager(ctx context.Context, managerID string) ([]GetAccommodationsByManagerRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsByManager, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsByManagerRow
	for rows.Next() {
		var i GetAccommodationsByManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Description,
			&i.Facilities,
			&i.GgMap,
			&i.Address,
			&i.Rules,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsByManagerWithPagination = `-- name: GetAccommodationsByManagerWithPagination :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `,
    ` + "`" + `is_deleted` + "`" + `,
    ` + "`" + `is_verified` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `is_deleted` + "`" + ` = 0
    AND ` + "`" + `manager_id` + "`" + ` = ?
LIMIT
    ?
OFFSET
    ?
`

type GetAccommodationsByManagerWithPaginationParams struct {
	ManagerID string
	Limit     int32
	Offset    int32
}

type GetAccommodationsByManagerWithPaginationRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Address     string
	Rules       json.RawMessage
	Rating      uint8
	IsDeleted   uint8
	IsVerified  uint8
}

func (q *Queries) GetAccommodationsByManagerWithPagination(ctx context.Context, arg GetAccommodationsByManagerWithPaginationParams) ([]GetAccommodationsByManagerWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsByManagerWithPagination, arg.ManagerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsByManagerWithPaginationRow
	for rows.Next() {
		var i GetAccommodationsByManagerWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Description,
			&i.Facilities,
			&i.GgMap,
			&i.Address,
			&i.Rules,
			&i.Rating,
			&i.IsDeleted,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsOfManagerWithPagination = `-- name: GetAccommodationsOfManagerWithPagination :many
SELECT
    id, manager_id, name, country, city, district, address, description, facilities, rating, gg_map, rules, is_verified, is_deleted, created_at, updated_at
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `manager_id` + "`" + ` = ?
LIMIT
    ?
OFFSET
    ?
`

type GetAccommodationsOfManagerWithPaginationParams struct {
	ManagerID string
	Limit     int32
	Offset    int32
}

func (q *Queries) GetAccommodationsOfManagerWithPagination(ctx context.Context, arg GetAccommodationsOfManagerWithPaginationParams) ([]EcommerceGoAccommodation, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsOfManagerWithPagination, arg.ManagerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EcommerceGoAccommodation
	for rows.Next() {
		var i EcommerceGoAccommodation
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Name,
			&i.Country,
			&i.City,
			&i.District,
			&i.Address,
			&i.Description,
			&i.Facilities,
			&i.Rating,
			&i.GgMap,
			&i.Rules,
			&i.IsVerified,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationsWithPagination = `-- name: GetAccommodationsWithPagination :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `manager_id` + "`" + `,
    ` + "`" + `country` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `city` + "`" + `,
    ` + "`" + `district` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `address` + "`" + `,
    ` + "`" + `gg_map` + "`" + `,
    ` + "`" + `rules` + "`" + `,
    ` + "`" + `rating` + "`" + `,
    ` + "`" + `is_deleted` + "`" + `,
    ` + "`" + `is_verified` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation` + "`" + `
WHERE
    ` + "`" + `is_deleted` + "`" + ` = 0 AND ` + "`" + `is_verified` + "`" + ` = 1
LIMIT
    ?
OFFSET
    ?
`

type GetAccommodationsWithPaginationParams struct {
	Limit  int32
	Offset int32
}

type GetAccommodationsWithPaginationRow struct {
	ID          string
	ManagerID   string
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	Address     string
	GgMap       string
	Rules       json.RawMessage
	Rating      uint8
	IsDeleted   uint8
	IsVerified  uint8
}

func (q *Queries) GetAccommodationsWithPagination(ctx context.Context, arg GetAccommodationsWithPaginationParams) ([]GetAccommodationsWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationsWithPaginationRow
	for rows.Next() {
		var i GetAccommodationsWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.Country,
			&i.Name,
			&i.City,
			&i.District,
			&i.Description,
			&i.Facilities,
			&i.Address,
			&i.GgMap,
			&i.Rules,
			&i.Rating,
			&i.IsDeleted,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAccommodation = `-- name: RestoreAccommodation :exec
UPDATE ` + "`" + `ecommerce_go_accommodation` + "`" + `
SET
    ` + "`" + `is_deleted` + "`" + ` = 0,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 1
`

type RestoreAccommodationParams struct {
	UpdatedAt uint64
	ID        string
}

func (q *Queries) RestoreAccommodation(ctx context.Context, arg RestoreAccommodationParams) error {
	_, err := q.db.ExecContext(ctx, restoreAccommodation, arg.UpdatedAt, arg.ID)
	return err
}

const updateAccommodation = `-- name: UpdateAccommodation :exec
UPDATE ` + "`" + `ecommerce_go_accommodation` + "`" + `
SET
    ` + "`" + `country` + "`" + ` = ?,
    ` + "`" + `name` + "`" + ` = ?,
    ` + "`" + `city` + "`" + ` = ?,
    ` + "`" + `district` + "`" + ` = ?,
    ` + "`" + `description` + "`" + ` = ?,
    ` + "`" + `facilities` + "`" + ` = ?,
    ` + "`" + `gg_map` + "`" + ` = ?,
    ` + "`" + `address` + "`" + ` = ?,
    ` + "`" + `rules` + "`" + ` = ?,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

type UpdateAccommodationParams struct {
	Country     string
	Name        string
	City        string
	District    string
	Description string
	Facilities  json.RawMessage
	GgMap       string
	Address     string
	Rules       json.RawMessage
	UpdatedAt   uint64
	ID          string
}

func (q *Queries) UpdateAccommodation(ctx context.Context, arg UpdateAccommodationParams) error {
	_, err := q.db.ExecContext(ctx, updateAccommodation,
		arg.Country,
		arg.Name,
		arg.City,
		arg.District,
		arg.Description,
		arg.Facilities,
		arg.GgMap,
		arg.Address,
		arg.Rules,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateStatusAccommodation = `-- name: UpdateStatusAccommodation :exec
UPDATE ` + "`" + `ecommerce_go_accommodation` + "`" + `
SET
    ` + "`" + `is_verified` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

type UpdateStatusAccommodationParams struct {
	IsVerified uint8
	ID         string
}

func (q *Queries) UpdateStatusAccommodation(ctx context.Context, arg UpdateStatusAccommodationParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusAccommodation, arg.IsVerified, arg.ID)
	return err
}
