// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: facility_detail.sql

package database

import (
	"context"
	"strings"
)

const createAccommodationFacilityDetail = `-- name: CreateAccommodationFacilityDetail :exec
INSERT INTO
    ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + ` (` + "`" + `id` + "`" + `, ` + "`" + `name` + "`" + `, ` + "`" + `created_at` + "`" + `, ` + "`" + `updated_at` + "`" + `)
VALUES
    (?, ?, ?, ?)
`

type CreateAccommodationFacilityDetailParams struct {
	ID        string
	Name      string
	CreatedAt uint64
	UpdatedAt uint64
}

func (q *Queries) CreateAccommodationFacilityDetail(ctx context.Context, arg CreateAccommodationFacilityDetailParams) error {
	_, err := q.db.ExecContext(ctx, createAccommodationFacilityDetail,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFacilityDetail = `-- name: DeleteFacilityDetail :exec
DELETE FROM ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

func (q *Queries) DeleteFacilityDetail(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFacilityDetail, id)
	return err
}

const getAccommodationFacilitiesByIds = `-- name: GetAccommodationFacilitiesByIds :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` IN (/*SLICE:ids*/?)
`

type GetAccommodationFacilitiesByIdsRow struct {
	ID   string
	Name string
}

func (q *Queries) GetAccommodationFacilitiesByIds(ctx context.Context, ids []string) ([]GetAccommodationFacilitiesByIdsRow, error) {
	query := getAccommodationFacilitiesByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationFacilitiesByIdsRow
	for rows.Next() {
		var i GetAccommodationFacilitiesByIdsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationFacilityDetail = `-- name: GetAccommodationFacilityDetail :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + `
`

type GetAccommodationFacilityDetailRow struct {
	ID   string
	Name string
}

func (q *Queries) GetAccommodationFacilityDetail(ctx context.Context) ([]GetAccommodationFacilityDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationFacilityDetail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationFacilityDetailRow
	for rows.Next() {
		var i GetAccommodationFacilityDetailRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccommodationFacilityDetailById = `-- name: GetAccommodationFacilityDetailById :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

type GetAccommodationFacilityDetailByIdRow struct {
	ID   string
	Name string
}

func (q *Queries) GetAccommodationFacilityDetailById(ctx context.Context, id string) (GetAccommodationFacilityDetailByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationFacilityDetailById, id)
	var i GetAccommodationFacilityDetailByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateFacilityDetail = `-- name: UpdateFacilityDetail :exec
UPDATE ` + "`" + `ecommerce_go_accommodation_detail_facility` + "`" + `
SET
    ` + "`" + `name` + "`" + ` = ?,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

type UpdateFacilityDetailParams struct {
	Name      string
	UpdatedAt uint64
	ID        string
}

func (q *Queries) UpdateFacilityDetail(ctx context.Context, arg UpdateFacilityDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateFacilityDetail, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
