// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_admin.sql

package database

import (
	"context"
)

const checkUserAdminExistsByEmail = `-- name: CheckUserAdminExistsByEmail :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_user_admin` + "`" + `
        WHERE
            ` + "`" + `account` + "`" + ` = ?
            AND ` + "`" + `is_deleted` + "`" + ` = 0
    )
`

func (q *Queries) CheckUserAdminExistsByEmail(ctx context.Context, account string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserAdminExistsByEmail, account)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserAdminExistsById = `-- name: CheckUserAdminExistsById :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_user_admin` + "`" + `
        WHERE
            ` + "`" + `id` + "`" + ` = ?
            AND ` + "`" + `is_deleted` + "`" + ` = 0
    )
`

func (q *Queries) CheckUserAdminExistsById(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserAdminExistsById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserAdmin = `-- name: CreateUserAdmin :exec
INSERT INTO
    ` + "`" + `ecommerce_go_user_admin` + "`" + ` (
        ` + "`" + `id` + "`" + `,
        ` + "`" + `account` + "`" + `,
        ` + "`" + `password` + "`" + `,
        ` + "`" + `created_at` + "`" + `,
        ` + "`" + `updated_at` + "`" + `
    )
VALUES
    (?, ?, ?, ?, ?)
`

type CreateUserAdminParams struct {
	ID        string
	Account   string
	Password  string
	CreatedAt uint64
	UpdatedAt uint64
}

func (q *Queries) CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, createUserAdmin,
		arg.ID,
		arg.Account,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserAdmin = `-- name: DeleteUserAdmin :exec
UPDATE ` + "`" + `ecommerce_go_user_admin` + "`" + `
SET
    ` + "`" + `is_deleted` + "`" + ` = 1
WHERE
    ` + "`" + `account` + "`" + ` = ?
`

func (q *Queries) DeleteUserAdmin(ctx context.Context, account string) error {
	_, err := q.db.ExecContext(ctx, deleteUserAdmin, account)
	return err
}

const getUserAdmin = `-- name: GetUserAdmin :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `account` + "`" + `,
    ` + "`" + `user_name` + "`" + `,
    ` + "`" + `password` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_admin` + "`" + `
WHERE
    ` + "`" + `account` + "`" + ` = ?
    AND ` + "`" + `is_deleted` + "`" + ` = 0
`

type GetUserAdminRow struct {
	ID       string
	Account  string
	UserName string
	Password string
}

func (q *Queries) GetUserAdmin(ctx context.Context, account string) (GetUserAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAdmin, account)
	var i GetUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.UserName,
		&i.Password,
	)
	return i, err
}

const updateUserAdminLogin = `-- name: UpdateUserAdminLogin :exec
UPDATE ` + "`" + `ecommerce_go_user_admin` + "`" + `
SET
    ` + "`" + `login_time` + "`" + ` = ?
WHERE
    ` + "`" + `account` + "`" + ` = ?
`

type UpdateUserAdminLoginParams struct {
	LoginTime uint64
	Account   string
}

func (q *Queries) UpdateUserAdminLogin(ctx context.Context, arg UpdateUserAdminLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAdminLogin, arg.LoginTime, arg.Account)
	return err
}
