// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_info.sql

package database

import (
	"context"
	"database/sql"
)

const checkUserInfoExists = `-- name: CheckUserInfoExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_user_info` + "`" + `
        WHERE
            ` + "`" + `id` + "`" + ` = ?
            AND ` + "`" + `is_deleted` + "`" + ` = 0
    )
`

func (q *Queries) CheckUserInfoExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserInfoExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserInfo = `-- name: CreateUserInfo :exec
INSERT INTO
    ` + "`" + `ecommerce_go_user_info` + "`" + ` (
        ` + "`" + `id` + "`" + `,
        ` + "`" + `account` + "`" + `,
        ` + "`" + `status` + "`" + `,
        ` + "`" + `is_authentication` + "`" + `,
        ` + "`" + `created_at` + "`" + `,
        ` + "`" + `updated_at` + "`" + `
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type CreateUserInfoParams struct {
	ID               string
	Account          string
	Status           uint8
	IsAuthentication uint8
	CreatedAt        uint64
	UpdatedAt        uint64
}

func (q *Queries) CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, createUserInfo,
		arg.ID,
		arg.Account,
		arg.Status,
		arg.IsAuthentication,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserInfo = `-- name: DeleteUserInfo :exec
DELETE FROM ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

func (q *Queries) DeleteUserInfo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserInfo, id)
	return err
}

const getEmailAndUsernameByID = `-- name: GetEmailAndUsernameByID :one
SELECT
    ` + "`" + `account` + "`" + `,
    ` + "`" + `user_name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
LIMIT
    1
`

type GetEmailAndUsernameByIDRow struct {
	Account  string
	UserName string
}

func (q *Queries) GetEmailAndUsernameByID(ctx context.Context, id string) (GetEmailAndUsernameByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailAndUsernameByID, id)
	var i GetEmailAndUsernameByIDRow
	err := row.Scan(&i.Account, &i.UserName)
	return i, err
}

const getNameAndImageUserInfo = `-- name: GetNameAndImageUserInfo :one
SELECT
    ` + "`" + `user_name` + "`" + `,
    ` + "`" + `image` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `account` + "`" + ` = ?
LIMIT
    1
`

type GetNameAndImageUserInfoRow struct {
	UserName string
	Image    string
}

func (q *Queries) GetNameAndImageUserInfo(ctx context.Context, account string) (GetNameAndImageUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getNameAndImageUserInfo, account)
	var i GetNameAndImageUserInfoRow
	err := row.Scan(&i.UserName, &i.Image)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `account` + "`" + `,
    ` + "`" + `user_name` + "`" + `,
    ` + "`" + `image` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `phone` + "`" + `,
    ` + "`" + `gender` + "`" + `,
    ` + "`" + `birthday` + "`" + `,
    ` + "`" + `email` + "`" + `,
    ` + "`" + `is_authentication` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `account` + "`" + ` = ?
LIMIT
    1
`

type GetUserInfoRow struct {
	ID               string
	Account          string
	UserName         string
	Image            string
	Status           uint8
	Phone            sql.NullString
	Gender           uint8
	Birthday         string
	Email            sql.NullString
	IsAuthentication uint8
}

func (q *Queries) GetUserInfo(ctx context.Context, account string) (GetUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, account)
	var i GetUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.UserName,
		&i.Image,
		&i.Status,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Email,
		&i.IsAuthentication,
	)
	return i, err
}

const getUserInfoByID = `-- name: GetUserInfoByID :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `account` + "`" + `,
    ` + "`" + `user_name` + "`" + `,
    ` + "`" + `image` + "`" + `,
    ` + "`" + `phone` + "`" + `,
    ` + "`" + `gender` + "`" + `,
    ` + "`" + `birthday` + "`" + `,
    ` + "`" + `email` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
LIMIT
    1
`

type GetUserInfoByIDRow struct {
	ID       string
	Account  string
	UserName string
	Image    string
	Phone    sql.NullString
	Gender   uint8
	Birthday string
	Email    sql.NullString
}

func (q *Queries) GetUserInfoByID(ctx context.Context, id string) (GetUserInfoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfoByID, id)
	var i GetUserInfoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.UserName,
		&i.Image,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Email,
	)
	return i, err
}

const getUserInfos = `-- name: GetUserInfos :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `account` + "`" + `,
    ` + "`" + `user_name` + "`" + `,
    ` + "`" + `image` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `phone` + "`" + `,
    ` + "`" + `gender` + "`" + `,
    ` + "`" + `birthday` + "`" + `,
    ` + "`" + `email` + "`" + `,
    ` + "`" + `is_authentication` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` IN (?)
`

type GetUserInfosRow struct {
	ID               string
	Account          string
	UserName         string
	Image            string
	Status           uint8
	Phone            sql.NullString
	Gender           uint8
	Birthday         string
	Email            sql.NullString
	IsAuthentication uint8
}

func (q *Queries) GetUserInfos(ctx context.Context, id string) ([]GetUserInfosRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserInfos, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInfosRow
	for rows.Next() {
		var i GetUserInfosRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.UserName,
			&i.Image,
			&i.Status,
			&i.Phone,
			&i.Gender,
			&i.Birthday,
			&i.Email,
			&i.IsAuthentication,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsernameByID = `-- name: GetUsernameByID :one
SELECT
    ` + "`" + `user_name` + "`" + `
FROM
    ` + "`" + `ecommerce_go_user_info` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
LIMIT
    1
`

func (q *Queries) GetUsernameByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsernameByID, id)
	var user_name string
	err := row.Scan(&user_name)
	return user_name, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE ` + "`" + `ecommerce_go_user_info` + "`" + `
SET
    ` + "`" + `image` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_authentication` + "`" + ` = 1
`

type UpdateUserAvatarParams struct {
	Image string
	ID    string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.Image, arg.ID)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE ` + "`" + `ecommerce_go_user_info` + "`" + `
SET
    ` + "`" + `user_name` + "`" + ` = ?,
    ` + "`" + `phone` + "`" + ` = ?,
    ` + "`" + `gender` + "`" + ` = ?,
    ` + "`" + `birthday` + "`" + ` = ?,
    -- ` + "`" + `email` + "`" + ` = ?,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    AND ` + "`" + `is_authentication` + "`" + ` = 1
`

type UpdateUserInfoParams struct {
	UserName  string
	Phone     sql.NullString
	Gender    uint8
	Birthday  string
	UpdatedAt uint64
	ID        string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo,
		arg.UserName,
		arg.Phone,
		arg.Gender,
		arg.Birthday,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
