// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_operator.sql

package database

import (
	"context"
)

const createUserOperator = `-- name: CreateUserOperator :exec
INSERT INTO
    ` + "`" + `ecommerce_go_user_operator` + "`" + ` (
        ` + "`" + `id` + "`" + `,
        ` + "`" + `user_id` + "`" + `,
        ` + "`" + `user_type` + "`" + `,
        ` + "`" + `created_at` + "`" + `,
        ` + "`" + `updated_at` + "`" + `
    )
VALUES
    (?, ?, ?, ?, ?)
`

type CreateUserOperatorParams struct {
	ID        string
	UserID    string
	UserType  EcommerceGoUserOperatorUserType
	CreatedAt uint64
	UpdatedAt uint64
}

func (q *Queries) CreateUserOperator(ctx context.Context, arg CreateUserOperatorParams) error {
	_, err := q.db.ExecContext(ctx, createUserOperator,
		arg.ID,
		arg.UserID,
		arg.UserType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
